import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Providers from "./providers";
import ColorToggle from "./components/ui-toggle/SwitchTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Louis Maucourt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
